"""
seed_scholarships.py — Directly seeds Supabase with curated Canadian scholarships.
Bypasses Gemini when rate-limited. Includes real amounts, logos, and images.

Usage: python seed_scholarships.py
"""

import os
import json
from supabase import create_client
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")

SCHOLARSHIPS = [
    {
        "title": "Horatio Alger Canadian Scholarship",
        "provider": "Horatio Alger Association",
        "amount": 25000,
        "deadline": "2026-10-25",
        "eligibility": "Need-based for grade 11 students from families with income under $80,000. Must demonstrate integrity, perseverance, and commitment to post-secondary education.",
        "location": "Canada",
        "program": "All",
        "gpa_requirement": 0.0,
        "financial_need_required": True,
        "academic_level": "High School, Undergraduate",
        "link": "https://www.horatioalger.ca/en/scholarships/",
        "logo_url": "https://horatioalger.ca/wp-content/uploads/2024/06/cropped-HAAC-Favicon-180x180.jpg",
        "image_url": "https://horatioalger.ca/wp-content/uploads/2024/05/HAA-Juniors-2023.jpg",
    },
    {
        "title": "RBC Ignite Scholarship",
        "provider": "RBC Royal Bank",
        "amount": 1500,
        "deadline": "2026-03-31",
        "eligibility": "For youth aged 16-20 seeking courses, certifications, or training 12 months or less. Must be Canadian citizen or permanent resident.",
        "location": "Canada",
        "program": "All",
        "gpa_requirement": 0.0,
        "financial_need_required": True,
        "academic_level": "Certification, Training",
        "link": "https://www.rbc.com/dms/enterprise/scholarships.html",
        "logo_url": "https://www.rbc.com/dvl/v1.0/assets/images/logos/rbc-logo-shield.svg",
        "image_url": "https://www.rbc.com/dvl/v1.0/assets/images/logos/rbc-logo-shield.svg",
    },
    {
        "title": "RBC Elevate Scholarship",
        "provider": "RBC Royal Bank",
        "amount": 15000,
        "deadline": "2026-03-26",
        "eligibility": "For individuals aged 17-29 pursuing post-secondary education in Canada. Must overcome financial barriers.",
        "location": "Canada",
        "program": "All",
        "gpa_requirement": 0.0,
        "financial_need_required": True,
        "academic_level": "Undergraduate, College",
        "link": "https://www.rbc.com/dms/enterprise/scholarships.html",
        "logo_url": "https://www.rbc.com/dvl/v1.0/assets/images/logos/rbc-logo-shield.svg",
        "image_url": "https://www.rbc.com/dvl/v1.0/assets/images/logos/rbc-logo-shield.svg",
    },
    {
        "title": "RBC Reimagine Scholarship",
        "provider": "RBC Royal Bank",
        "amount": 5000,
        "deadline": "2026-06-04",
        "eligibility": "For adult learners 25+ who have been out of school 3+ years seeking upskilling or reskilling.",
        "location": "Canada",
        "program": "All",
        "gpa_requirement": 0.0,
        "financial_need_required": True,
        "academic_level": "Post-Graduate, Masters, Certification",
        "link": "https://www.rbc.com/dms/enterprise/scholarships.html",
        "logo_url": "https://www.rbc.com/dvl/v1.0/assets/images/logos/rbc-logo-shield.svg",
        "image_url": "https://www.rbc.com/dvl/v1.0/assets/images/logos/rbc-logo-shield.svg",
    },
    {
        "title": "Loran Award",
        "provider": "Loran Scholars Foundation",
        "amount": 100000,
        "deadline": "2026-10-15",
        "eligibility": "Canada's largest undergraduate award. For students demonstrating character, service, and leadership. Includes tuition, mentorship, and summer stipends over 4 years.",
        "location": "Canada",
        "program": "All",
        "gpa_requirement": 3.3,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://loranscholar.ca/the-program/",
        "logo_url": "https://loranscholar.ca/wp-content/uploads/2024/02/Website-Favicon.png",
        "image_url": "https://loranscholar.ca/wp-content/uploads/2023/07/logo.svg",
    },
    {
        "title": "Schulich Leader Scholarship",
        "provider": "Schulich Foundation",
        "amount": 120000,
        "deadline": "2026-02-01",
        "eligibility": "For students entering STEM programs at participating Canadian universities. Must demonstrate academic excellence and community leadership.",
        "location": "Canada",
        "program": "STEM",
        "gpa_requirement": 3.7,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://schulichleaders.com/",
        "logo_url": "https://schulichleaders.com/wp-content/uploads/2023/07/favicon.png",
        "image_url": "https://schulichleaders.com/wp-content/uploads/2023/07/logo.svg",
    },
    {
        "title": "Vanier Canada Graduate Scholarship",
        "provider": "Government of Canada",
        "amount": 50000,
        "deadline": "2026-11-01",
        "eligibility": "For doctoral students demonstrating academic excellence, research potential, and leadership. $50,000/year for 3 years.",
        "location": "Canada",
        "program": "All",
        "gpa_requirement": 3.8,
        "financial_need_required": False,
        "academic_level": "PhD",
        "link": "https://vanier.gc.ca/",
        "logo_url": "https://www.canada.ca/etc/designs/canada/wet-boew/assets/favicon.ico",
        "image_url": "https://www.canada.ca/content/dam/canada/splash/en-francais.jpg",
    },
    {
        "title": "Canada Graduate Scholarship – Master's (CGS-M)",
        "provider": "Government of Canada",
        "amount": 17500,
        "deadline": "2026-12-01",
        "eligibility": "For Canadian citizens or permanent residents pursuing a master's degree. $17,500 for one year.",
        "location": "Canada",
        "program": "All",
        "gpa_requirement": 3.5,
        "financial_need_required": False,
        "academic_level": "Masters",
        "link": "https://www.nserc-crsng.gc.ca/Students-Etudiants/PG-CS/CGSM-BESCM_eng.asp",
        "logo_url": "https://www.canada.ca/etc/designs/canada/wet-boew/assets/favicon.ico",
        "image_url": "https://www.canada.ca/content/dam/canada/splash/en-francais.jpg",
    },
    {
        "title": "Ontario Graduate Scholarship (OGS)",
        "provider": "Province of Ontario",
        "amount": 15000,
        "deadline": "2026-02-15",
        "eligibility": "Merit-based award for master's or doctoral students at Ontario universities. $5,000 per term for 2-3 terms.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.0,
        "financial_need_required": False,
        "academic_level": "Masters, PhD",
        "link": "https://osap.gov.on.ca/OSAPPortal/en/A-ZListofAid/PRDR019245.html",
        "logo_url": "https://www.ontario.ca/themes/ontario_flavour/favicon.ico",
        "image_url": "https://www.ontario.ca/themes/ontario_flavour/logo.svg",
    },
    {
        "title": "Waterloo President's Scholarship",
        "provider": "University of Waterloo",
        "amount": 10000,
        "deadline": "2026-02-01",
        "eligibility": "Automatic entrance scholarship for students admitted with 95%+ average. No application required.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.9,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://uwaterloo.ca/future-students/financing/scholarships",
        "logo_url": "https://uwaterloo.ca/future-students/profiles/uw_base_profile/themes/uw_fdsu_theme_flavour/favicon.ico",
        "image_url": "https://uwaterloo.ca/future-students/sites/default/files/uploads/images/instagram-5.jpg",
    },
    {
        "title": "Waterloo Merit Scholarship",
        "provider": "University of Waterloo",
        "amount": 5000,
        "deadline": "2026-02-01",
        "eligibility": "For students admitted with 90-94.9% average. Automatic, no application required.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.7,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://uwaterloo.ca/future-students/financing/scholarships",
        "logo_url": "https://uwaterloo.ca/future-students/profiles/uw_base_profile/themes/uw_fdsu_theme_flavour/favicon.ico",
        "image_url": "https://uwaterloo.ca/future-students/sites/default/files/uploads/images/instagram-5.jpg",
    },
    {
        "title": "Waterloo Engineering Entrance Scholarship",
        "provider": "University of Waterloo",
        "amount": 4000,
        "deadline": "2026-03-31",
        "eligibility": "For students entering engineering programs with strong academic records and extracurriculars.",
        "location": "Ontario",
        "program": "Engineering",
        "gpa_requirement": 3.5,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://uwaterloo.ca/future-students/financing/scholarships",
        "logo_url": "https://uwaterloo.ca/future-students/profiles/uw_base_profile/themes/uw_fdsu_theme_flavour/favicon.ico",
        "image_url": "https://uwaterloo.ca/future-students/sites/default/files/uploads/images/instagram-5.jpg",
    },
    {
        "title": "McGill Major Entrance Scholarship",
        "provider": "McGill University",
        "amount": 12000,
        "deadline": "2026-01-15",
        "eligibility": "Renewable entrance scholarship for outstanding incoming undergraduates. $3,000/year for 4 years.",
        "location": "Quebec",
        "program": "All",
        "gpa_requirement": 3.8,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://mcgill.ca/studentaid/scholarships-aid/future-undergrads/entrance-scholarships",
        "logo_url": "https://www.mcgill.ca/sites/all/themes/flavor_flavor/favicon.ico",
        "image_url": "https://www.mcgill.ca/sites/all/themes/moriarty/images/mcgill_crest.png",
    },
    {
        "title": "McGill One Entrance Scholarship",
        "provider": "McGill University",
        "amount": 3000,
        "deadline": "2026-01-15",
        "eligibility": "One-time entrance scholarship for strong incoming students. Based on academic excellence.",
        "location": "Quebec",
        "program": "All",
        "gpa_requirement": 3.5,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://mcgill.ca/studentaid/scholarships-aid/future-undergrads/entrance-scholarships",
        "logo_url": "https://www.mcgill.ca/sites/all/themes/flavor_flavor/favicon.ico",
        "image_url": "https://www.mcgill.ca/sites/all/themes/moriarty/images/mcgill_crest.png",
    },
    {
        "title": "U of T President's Scholars of Excellence",
        "provider": "University of Toronto",
        "amount": 10000,
        "deadline": "2026-11-21",
        "eligibility": "For incoming students with exceptional academic and extracurricular achievements. Renewable.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.9,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://future.utoronto.ca/finances/scholarships/",
        "logo_url": "https://future.utoronto.ca/themes/utfs/favicon.ico",
        "image_url": "https://future.utoronto.ca/sites/default/files/styles/landscape_16_9_900/public/2020-03/UofT_Convocation_Hall.jpg",
    },
    {
        "title": "U of T National Scholarship",
        "provider": "University of Toronto",
        "amount": 5000,
        "deadline": "2026-11-21",
        "eligibility": "For incoming Canadian students demonstrating academic excellence and community involvement.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.7,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://future.utoronto.ca/finances/scholarships/",
        "logo_url": "https://future.utoronto.ca/themes/utfs/favicon.ico",
        "image_url": "https://future.utoronto.ca/sites/default/files/styles/landscape_16_9_900/public/2020-03/UofT_Convocation_Hall.jpg",
    },
    {
        "title": "TMU President's Entrance Scholarship",
        "provider": "Toronto Metropolitan University",
        "amount": 10000,
        "deadline": "2026-02-01",
        "eligibility": "For students entering TMU with 92%+ average. Includes $2,500 renewable for 4 years.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.8,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://www.torontomu.ca/admissions/scholarships-awards/",
        "logo_url": "https://www.torontomu.ca/content/dam/tmu_favicon.ico",
        "image_url": "https://www.torontomu.ca/etc.clientlibs/ryecms/static/clientlib-site/resources/images/tmu-logo.svg",
    },
    {
        "title": "TMU Entrance Scholarship",
        "provider": "Toronto Metropolitan University",
        "amount": 2500,
        "deadline": "2026-02-01",
        "eligibility": "For students entering TMU with 80-91.9% average. One-time award.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.3,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://www.torontomu.ca/admissions/scholarships-awards/",
        "logo_url": "https://www.torontomu.ca/content/dam/tmu_favicon.ico",
        "image_url": "https://www.torontomu.ca/etc.clientlibs/ryecms/static/clientlib-site/resources/images/tmu-logo.svg",
    },
    {
        "title": "Concordia University Entrance Bursary",
        "provider": "Concordia University",
        "amount": 3000,
        "deadline": "2026-04-10",
        "eligibility": "For newly admitted undergraduate students with demonstrated financial need.",
        "location": "Quebec",
        "program": "All",
        "gpa_requirement": 0.0,
        "financial_need_required": True,
        "academic_level": "Undergraduate",
        "link": "https://www.concordia.ca/students/financial/scholarships-funding/bursaries.html",
        "logo_url": "https://www.concordia.ca/etc/designs/concordia/clientlibs/img/favicons/apple-touch-icon.png",
        "image_url": "https://www.concordia.ca/content/concordia/en/students/financial/scholarships-funding/bursaries.social.png/1718639211301.jpg",
    },
    {
        "title": "Dalhousie Entrance Scholarship",
        "provider": "Dalhousie University",
        "amount": 40000,
        "deadline": "2026-03-01",
        "eligibility": "Renewable entrance scholarship up to $10,000/year for 4 years for top incoming students.",
        "location": "Nova Scotia",
        "program": "All",
        "gpa_requirement": 3.8,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://www.dal.ca/admissions/money_matters/awards-financial-aid/scholarships.html",
        "logo_url": "https://cdn.dal.ca/etc/designs/dalhousie/clientlibs/global/default/images/favicon.ico",
        "image_url": "https://cdn.dal.ca/_jcr_content/og_image.adaptive.full.high.jpg/1655131802257.jpg",
    },
    {
        "title": "Carleton University Prestige Scholarship",
        "provider": "Carleton University",
        "amount": 16000,
        "deadline": "2026-03-01",
        "eligibility": "For students with 95%+ entering Carleton. $4,000/year renewable for 4 years.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.9,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://carleton.ca/awards/scholarships/",
        "logo_url": "https://cdn.carleton.ca/rds/assets/favicons/apple-touch-icon.png",
        "image_url": "https://cdn.carleton.ca/rds/assets/cu-logos/cu-logo-color-right-horiztonal.svg",
    },
    {
        "title": "Carleton Entrance Scholarship",
        "provider": "Carleton University",
        "amount": 4000,
        "deadline": "2026-03-01",
        "eligibility": "Automatic scholarship for students with 80-94.9% average. One-time award.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.3,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://carleton.ca/awards/scholarships/",
        "logo_url": "https://cdn.carleton.ca/rds/assets/favicons/apple-touch-icon.png",
        "image_url": "https://cdn.carleton.ca/rds/assets/cu-logos/cu-logo-color-right-horiztonal.svg",
    },
    {
        "title": "Pierre Elliott Trudeau Foundation Scholarship",
        "provider": "Trudeau Foundation",
        "amount": 60000,
        "deadline": "2026-12-01",
        "eligibility": "For doctoral students in humanities and social sciences. $60,000/year for up to 4 years, plus travel/networking.",
        "location": "Canada",
        "program": "Social Sciences, Humanities",
        "gpa_requirement": 3.7,
        "financial_need_required": False,
        "academic_level": "PhD",
        "link": "https://www.trudeaufoundation.ca/",
        "logo_url": "https://www.trudeaufoundation.ca/themes/custom/tff/favicon.ico",
        "image_url": "https://www.trudeaufoundation.ca/themes/custom/tff/logo.svg",
    },
    {
        "title": "TD Scholarship for Community Leadership",
        "provider": "TD Bank",
        "amount": 70000,
        "deadline": "2026-01-15",
        "eligibility": "Up to 20 scholarships awarded annually to students who demonstrate community leadership. Covers tuition, living expenses, and mentoring.",
        "location": "Canada",
        "program": "All",
        "gpa_requirement": 3.0,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://www.td.com/ca/en/about-td/ready-commitment/vibrant-planet/scholarships",
        "logo_url": "https://www.td.com/content/dam/tdct/images/td-logo.svg",
        "image_url": "https://www.td.com/content/dam/tdct/images/td-logo.svg",
    },
    {
        "title": "Banting Postdoctoral Fellowship",
        "provider": "Government of Canada",
        "amount": 70000,
        "deadline": "2026-09-20",
        "eligibility": "For postdoctoral researchers in health, natural sciences, engineering, and social sciences. $70,000/year for 2 years.",
        "location": "Canada",
        "program": "STEM, Health, Social Sciences",
        "gpa_requirement": 3.8,
        "financial_need_required": False,
        "academic_level": "Postdoctoral",
        "link": "https://banting.fellowships-bourses.gc.ca/",
        "logo_url": "https://www.canada.ca/etc/designs/canada/wet-boew/assets/favicon.ico",
        "image_url": "https://www.canada.ca/content/dam/canada/splash/en-francais.jpg",
    },
    {
        "title": "McCall MacBain Scholarship",
        "provider": "McGill University",
        "amount": 80000,
        "deadline": "2026-08-18",
        "eligibility": "Fully funded graduate scholarship at McGill for master's or professional studies. Covers tuition plus $2,000/month living stipend.",
        "location": "Quebec",
        "program": "All",
        "gpa_requirement": 3.7,
        "financial_need_required": False,
        "academic_level": "Masters",
        "link": "https://www.mcgill.ca/mccall-macbain-scholarships/",
        "logo_url": "https://www.mcgill.ca/sites/all/themes/flavor_flavor/favicon.ico",
        "image_url": "https://www.mcgill.ca/sites/all/themes/moriarty/images/mcgill_crest.png",
    },
    {
        "title": "UBC International Major Entrance Scholarship",
        "provider": "University of British Columbia",
        "amount": 25000,
        "deadline": "2026-01-15",
        "eligibility": "For outstanding international students entering UBC. Up to $25,000/year renewable.",
        "location": "British Columbia",
        "program": "All",
        "gpa_requirement": 3.8,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://you.ubc.ca/financial-planning/scholarships-awards-financial-support/",
        "logo_url": "https://cdn.ubc.ca/clf/7.0.4/img/favicon.ico",
        "image_url": "https://cdn.ubc.ca/clf/7.0.4/img/ubc-logo.png",
    },
    {
        "title": "York University President's Scholarship",
        "provider": "York University",
        "amount": 45000,
        "deadline": "2026-02-01",
        "eligibility": "Renewable entrance scholarship for students with 95%+ average. Up to $11,250/year for 4 years.",
        "location": "Ontario",
        "program": "All",
        "gpa_requirement": 3.9,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://www.yorku.ca/admissions/awards-and-scholarships/",
        "logo_url": "https://www.yorku.ca/wp-content/themes/flavor/favicon.ico",
        "image_url": "https://www.yorku.ca/wp-content/themes/flavor/images/yorku-logo.svg",
    },
    {
        "title": "University of Calgary Entrance Award",
        "provider": "University of Calgary",
        "amount": 60000,
        "deadline": "2026-12-01",
        "eligibility": "For exceptional incoming students. Up to $15,000/year for 4 years based on academic excellence.",
        "location": "Alberta",
        "program": "All",
        "gpa_requirement": 3.8,
        "financial_need_required": False,
        "academic_level": "Undergraduate",
        "link": "https://www.ucalgary.ca/registrar/finances/awards-scholarships-and-bursaries/entrance",
        "logo_url": "https://www.ucalgary.ca/themes/ucalgary/ucws_theme/apple-touch-icon.png",
        "image_url": "https://www.ucalgary.ca/modules/ucalgary/ucws_common/ucws_core/images/ucalgary-header.svg",
    },
    {
        "title": "Horatio Alger Vocational Scholarship",
        "provider": "Horatio Alger Association",
        "amount": 9000,
        "deadline": "2026-10-25",
        "eligibility": "For students pursuing a certificate or diploma program. Aimed at vocational and technical career aspirations.",
        "location": "Canada",
        "program": "Vocational, Technical",
        "gpa_requirement": 0.0,
        "financial_need_required": True,
        "academic_level": "Certificate, Diploma",
        "link": "https://www.horatioalger.ca/en/scholarships/",
        "logo_url": "https://horatioalger.ca/wp-content/uploads/2024/06/cropped-HAAC-Favicon-180x180.jpg",
        "image_url": "https://horatioalger.ca/wp-content/uploads/2024/05/HAA-Juniors-2023.jpg",
    },
]


def seed():
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("❌ Missing SUPABASE_URL or SUPABASE_KEY in .env")
        return

    db = create_client(SUPABASE_URL, SUPABASE_KEY)

    # First, clear existing data to avoid duplicates
    print("🗑️  Clearing existing scholarship data...")
    try:
        db.table("scholarships").delete().neq("id", 0).execute()
        print("   Cleared.")
    except Exception as e:
        print(f"   Warning: {e}")

    inserted = 0
    for s in SCHOLARSHIPS:
        try:
            db.table("scholarships").insert(s).execute()
            inserted += 1
            print(f"  ✅ {s['title']} (${s['amount']:,})")
        except Exception as e:
            print(f"  ❌ {s['title']}: {e}")

    print(f"\n🎉 Done — {inserted}/{len(SCHOLARSHIPS)} scholarships seeded!")


if __name__ == "__main__":
    seed()
